[package]
name = "pdfpdf"
version = "0.1.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>",
	   "Rasmus Kaj <rasmus@krats.se>",
	   "Benjamin Kimock <kimockb@gmail.com>"]
license = "MIT"
description = """
Generate PDF files in pure Rust.
Currently, simple vector graphics and text set in the 14 built-in \
fonts are supported."""
documentation = "https://docs.rs/pdfpdf"
repository = "https://github.com/saethlin/pdfpdf"
readme = "README.md"

build = "src/build_metrics.rs"

[build-dependencies]
lazy_static = "0.2"

[dependencies]
lazy_static = "0.2"
time = "0.1"
deflate = "0.7"

[profile.release]
lto = true
panic = 'abort'
