[package]
name = "pdfpdf"
version = "0.1.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>",
	   "Rasmus Kaj <rasmus@krats.se>",
	   "Benjamin Kimock <kimockb@gmail.com>"]
license = "MIT"
description = """
Generate PDF files in pure Rust.
Currently, simple vector graphics are supported."""
documentation = "https://docs.rs/pdfpdf"
repository = "https://github.com/saethlin/pdfpdf"
readme = "README.md"

[dependencies]
deflate = "0.7"

[profile.release]
lto = true
panic = 'abort'
